blank_issues_enabled: false
contact_links:
  - name: Support and Questions for Apprise Core
    url: https://github.com/caronc/apprise/discussions
    about: Please use Discussions for questions and general support.
  - name: Support and Questions for Apprise API
    url: https://github.com/caronc/apprise-api/discussions
    about: Please use Discussions for questions and general support.

